// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8-fmMAImR08JTjUF_2iZi01fteVOFdck',
    appId: '1:391033361167:web:2c912e53bb7b4a44e2a47a',
    messagingSenderId: '391033361167',
    projectId: 'cosmoquizz-5d015',
    authDomain: 'cosmoquizz-5d015.firebaseapp.com',
    storageBucket: 'cosmoquizz-5d015.appspot.com',
    measurementId: 'G-KC5C0F9V35',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7gmcLrqzdz7FpFRZ7rVUkpjWVmf5h43k',
    appId: '1:391033361167:android:d8af1629bdab6aa7e2a47a',
    messagingSenderId: '391033361167',
    projectId: 'cosmoquizz-5d015',
    storageBucket: 'cosmoquizz-5d015.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZegsyIh2qx-KkDC-DUlxXlWq0rey03Eg',
    appId: '1:391033361167:ios:c714fdb60b367911e2a47a',
    messagingSenderId: '391033361167',
    projectId: 'cosmoquizz-5d015',
    storageBucket: 'cosmoquizz-5d015.appspot.com',
    iosClientId: '391033361167-pmosu8vcj5v0m52an2f1u1h7h8ois3lh.apps.googleusercontent.com',
    iosBundleId: '5d015',
  );
}
